services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    command: start-dev --import-realm
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=preview
    volumes:
      - ./dev-realm.json:/opt/keycloak/data/import/dev-realm.json
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=guessers
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  guessers-app:
    image: hachiko2k/guessers-server:0.0.3
    container_name: guessers_server
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c
      "while ! curl -f http://keycloak:8080/realms/guessers/.well-known/openid-configuration; do
         echo 'Waiting for Keycloak...'; sleep 5;
       done;
       java -jar guessers.jar"
volumes:
  postgres_data: